export const GET_DOCS_SUCCESS = "GET_DOCS_SUCCESS";
export const DOCS_IS_LOADING = "DOCS_IS_LOADING";

export const GET_SVEDEN_SUCCESS = "GET_SVEDEN_SUCCESS";
export const SVEDEN_IS_LOADING = "SVEDEN_IS_LOADING";

export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const EXAM_IS_LOADING = "EXAM_IS_LOADING";

export const GET_KONKURS_LIST_SUCCESS = "GET_KONKURS_LIST_SUCCESS";
export const KONKURS_LIST_IS_LOADING = "KONKURS_LIST_IS_LOADING";
export const SET_KONKURS_LIST = "SET_KONKURS_LIST";
export const GET_FAKS_LIST_FOR_KONKURS = "GET_FAKS_LIST_FOR_KONKURS";
export const GET_EDU_FORMS_LIST_FOR_KONKURS = "GET_EDU_FORMS_LIST_FOR_KONKURS";
export const GET_BASE_FOR_KONKURS = "GET_BASE_FOR_KONKURS";
export const KONKURS_RESET = "KONKURS_RESET";

export const GET_ENROLLED_LIST_SUCCESS = "GET_ENROLLED_LIST_SUCCESS";
export const ENROLLED_LIST_IS_LOADING = "ENROLLED_LIST_IS_LOADING";
export const SET_ENROLLED_LIST = "SET_ENROLLED_LIST";
export const GET_FAKS_LIST_FOR_ENROLLED = "GET_FAKS_LIST_FOR_ENROLLED";
export const GET_EDU_FORMS_LIST_FOR_ENROLLED = "GET_EDU_FORMS_LIST_FOR_ENROLLED";
export const GET_BASE_FOR_ENROLLED = "GET_BASE_FOR_ENROLLED";
export const ENROLLED_RESET = "ENROLLED_RESET";

export const IS_ERROR = "IS_ERROR";

export const GET_TARGETS_SELECT = "GET_TARGETS_SELECT";
export const SET_TARGET_SELECT = "SET_TARGET_SELECT";
export const CHECK_TARGET_IS_SELECT = "CHECK_TARGET_IS_SELECT";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const VIEW_FILE = "VIEW_FILE";